#pragma once
#include <Arduino.h>
static const char WEB_PAGE[] PROGMEM = R"HTML(<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>FlightDot</title>
<style>body{background:#07100e;color:#e6f6eb;font:16px system-ui;max-width:700px;margin:40px auto;padding:0 22px}h1{font-weight:500}small,p{color:#9fb5a8;line-height:1.6}section{background:#10201a;border:1px solid #284735;border-radius:16px;padding:22px;margin:20px 0}label{display:block;margin:14px 0 5px}input,select,button{font:inherit;padding:12px;border:1px solid #386349;border-radius:8px;background:#07100e;color:inherit;box-sizing:border-box;max-width:100%}input,select{width:100%}button{cursor:pointer;margin:8px 5px 2px 0;background:#193e2a}button.primary{background:#8bf3ae;color:#07100e}#message,#placeMessage,#followStatus{white-space:pre-wrap;color:#a8fac1}</style>
<h1>◉ FlightDot</h1><p id="live">Connecting…</p><p id="message" role="status"></p>
<section id="wifi"><h2>Wi-Fi</h2><p id="wifiInfo">Checking connection…</p><button type="button" id="scanWifi">Scan available networks</button><div id="wifiNetworks"></div><form id="wifiForm"><input name="ssid" type="hidden"><p id="selectedWifi">Select a network from the list.</p><label>Network password</label><input name="password" type="password" maxlength="63" autocomplete="new-password"><button class="primary" id="connectWifi" disabled>Save and connect</button></form></section>
<section><h2>Search</h2><form id="placeSearch"><label for="placeQuery">City or airport</label><input id="placeQuery" maxlength="100" required><button class="primary">Search location</button></form><p id="placeMessage" role="status"></p><div id="placeResults"></div><form id="flightSearch"><label for="flightQuery">Flight number or callsign</label><input id="flightQuery" maxlength="16" required autocapitalize="characters"><button class="primary">Follow aircraft</button><button type="button" id="stopFollow" hidden>Stop following</button></form><p id="followStatus" role="status"></p></section>
<section><h2>Radar</h2><form id="settings"><input name="lat" type="hidden"><input name="lon" type="hidden"><input name="centerName" type="hidden"><label for="rangeKm">Range (km)</label><select name="rangeKm" id="rangeKm" required><option value="50">50 km</option><option value="100">100 km</option><option value="150">150 km</option><option value="200">200 km</option><option value="250">250 km</option></select><label>Brightness (10–255)</label><input name="brightness" type="range" min="10" max="255"><label><input name="sweep" type="checkbox" style="width:auto"> Sweep line</label><button class="primary">Save settings</button></form></section>
<script>
let token='',airportsPromise,placeBusy=false,lastPlaceSearch=0;const form=document.querySelector('#settings'),msg=t=>document.querySelector('#message').textContent=t,el=n=>form.elements.namedItem(n),wifiInfo=document.querySelector('#wifiInfo'),wifiForm=document.querySelector('#wifiForm'),wifiNetworks=document.querySelector('#wifiNetworks'),scanWifi=document.querySelector('#scanWifi'),selectedWifi=document.querySelector('#selectedWifi'),connectWifi=document.querySelector('#connectWifi');
async function api(path,data){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','X-Radar-Token':token},body:new URLSearchParams(data)}),text=await r.text();if(!r.ok)throw Error(text);return text}async function apiJson(path,data={}){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','X-Radar-Token':token},body:new URLSearchParams(data)}),text=await r.text();if(!r.ok&&r.status!==202)throw Error(text);return JSON.parse(text)}
function setCenter(lat,lon,name){el('lat').value=lat;el('lon').value=lon;el('centerName').value=name.slice(0,30)}
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
function airportIndex(){if(!airportsPromise)airportsPromise=fetch('/api/airports').then(r=>{if(!r.ok)throw Error('Could not load airports');return r.json()}).catch(e=>{airportsPromise=null;throw e});return airportsPromise}
async function cities(q){const key='city-v1:'+normalize(q);let saved;try{saved=JSON.parse(localStorage.getItem(key))}catch(e){}if(saved&&Date.now()-saved.at<86400000)return saved.items;const r=await fetch('https://geocoding-api.open-meteo.com/v1/search?'+new URLSearchParams({name:q,count:'8',language:'en',format:'json'}),{signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('City search is unavailable');const body=await r.json(),items=(body.results||[]).map(x=>({name:[x.name,x.admin1,x.country].filter(Boolean).join(' · '),label:x.name,lat:x.latitude,lon:x.longitude,kind:'City'}));try{localStorage.setItem(key,JSON.stringify({at:Date.now(),items}))}catch(e){}return items}
document.querySelector('#placeSearch').onsubmit=async e=>{e.preventDefault();if(placeBusy||Date.now()-lastPlaceSearch<1200)return;placeBusy=true;lastPlaceSearch=Date.now();const btn=e.target.querySelector('button'),info=document.querySelector('#placeMessage'),results=document.querySelector('#placeResults');btn.disabled=true;results.replaceChildren();info.textContent='Searching…';const query=document.querySelector('#placeQuery').value.trim(),q=normalize(query);try{if(q.length<2)throw Error('Enter at least two characters.');const found=await Promise.allSettled([airportIndex(),cities(query)]);let items=[];if(found[0].status==='fulfilled')items=found[0].value.filter(a=>normalize(a.slice(0,5).join(' ')).includes(q)).sort((a,b)=>{const score=x=>(normalize(x[2])===q||normalize(x[3])===q?100:0)+(x[4]==='BR'?10:0)+(x[2]?1:0);return score(b)-score(a)}).slice(0,8).map(a=>({name:[a[0],a[1],[a[2],a[3]].filter(Boolean).join('/'),a[4]].filter(Boolean).join(' · '),label:a[1]||a[0],lat:a[5],lon:a[6],kind:'Airport'}));if(found[1].status==='fulfilled')items.push(...found[1].value);for(const item of items){const b=document.createElement('button');b.type='button';b.style.cssText='display:block;width:100%;text-align:left';b.textContent=item.kind+': '+item.name;b.onclick=async()=>{b.disabled=true;try{await api('/api/follow',{query:''});setCenter(item.lat,item.lon,item.label);await saveSettings();info.textContent='Centred on '+item.label}catch(e){info.textContent=e.message}finally{b.disabled=false}};results.append(b)}info.textContent=items.length?'Choose a result.':'No locations found.'}catch(e){info.textContent=e.message}finally{btn.disabled=false;placeBusy=false}};
document.querySelector('#flightSearch').onsubmit=async e=>{e.preventDefault();try{msg(await api('/api/follow',{query:document.querySelector('#flightQuery').value}));await status()}catch(e){msg(e.message)}};document.querySelector('#stopFollow').onclick=async()=>{try{msg(await api('/api/follow',{query:''}));await status()}catch(e){msg(e.message)}};
async function saveSettings(){let d=Object.fromEntries(new FormData(form));d.sweep=el('sweep').checked?'1':'0';const result=await api('/api/config',d);msg(result);return result}form.onsubmit=async e=>{e.preventDefault();try{await saveSettings()}catch(e){msg(e.message)}};wifiForm.onsubmit=async e=>{e.preventDefault();if(!wifiForm.elements.ssid.value){wifiInfo.textContent='Choose a network from the list first.';return}try{msg(await api('/api/wifi',Object.fromEntries(new FormData(e.target))));wifiInfo.textContent='Changing networks… reconnect to the new Wi-Fi and open flightdot.local.';wifiForm.elements.password.value='';connectWifi.disabled=true}catch(e){msg(e.message)}};scanWifi.onclick=async()=>{scanWifi.disabled=true;wifiNetworks.textContent='Scanning networks…';try{let result;do{result=await apiJson('/api/wifi/scan');if(result.scanning)await new Promise(r=>setTimeout(r,550))}while(result.scanning);wifiNetworks.replaceChildren();if(!result.networks.length){wifiNetworks.textContent='No networks found.';return}for(const network of result.networks){const b=document.createElement('button');b.type='button';b.style.cssText='display:block;width:100%;text-align:left';b.textContent=`${signalBars(network.rssi)} ${network.ssid} · ${network.rssi} dBm${network.secure?' · password required':' · open'}`;b.onclick=()=>{wifiForm.elements.ssid.value=network.ssid;wifiForm.elements.password.value='';selectedWifi.textContent='Selected network: '+network.ssid;connectWifi.disabled=false;wifiForm.elements.password.focus()};wifiNetworks.append(b)}}catch(e){wifiNetworks.textContent='Could not scan networks: '+e.message}finally{scanWifi.disabled=false}};
function signalBars(rssi){if(!Number.isFinite(rssi))return '▯▯▯▯';const n=rssi>=-55?4:rssi>=-65?3:rssi>=-75?2:1;return '▮'.repeat(n)+'▯'.repeat(4-n)}async function start(){try{const s=await(await fetch('/api/config')).json();token=s.token;for(const k of ['lat','lon','centerName','rangeKm','brightness'])el(k).value=s[k];if(!el('rangeKm').value)el('rangeKm').value='150';el('sweep').checked=s.sweep}catch(e){msg('Could not load settings: '+e.message)}}async function status(){try{const s=await(await fetch('/api/status')).json();document.querySelector('#live').textContent=`${s.wifi?'Connected':'Wi-Fi setup'} · ${s.count} aircraft · ${s.provider||'waiting'}${s.error?' · '+s.error:''}`;wifiInfo.textContent=s.wifi?`Connected to ${s.ssid||'unnamed network'} · ${signalBars(s.rssi)} ${s.rssi} dBm`:'No Wi-Fi connection. Scan and select a network below.';document.querySelector('#stopFollow').hidden=!s.follow;document.querySelector('#followStatus').textContent=s.follow?`${s.target?'Following':'Looking for'} ${s.follow}${s.target?' · '+s.target.callsign:''}`:''}catch(e){wifiInfo.textContent='Could not check Wi-Fi status.'}}start();status();setInterval(status,5000);
</script></html>)HTML";
