#pragma once
#include <Arduino.h>
static const char WEB_PAGE[] PROGMEM = R"HTML(<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>FlightDot</title>
<style>body{background:#07100e;color:#e6f6eb;font:16px system-ui;max-width:700px;margin:40px auto;padding:0 22px}h1{font-weight:500}small,p{color:#9fb5a8;line-height:1.6}section{background:#10201a;border:1px solid #284735;border-radius:16px;padding:22px;margin:20px 0}label{display:block;margin:14px 0 5px}input,select,button{font:inherit;padding:12px;border:1px solid #386349;border-radius:8px;background:#07100e;color:inherit;box-sizing:border-box;max-width:100%}input,select{width:100%}button{cursor:pointer;margin:8px 5px 2px 0;background:#193e2a}button.primary{background:#8bf3ae;color:#07100e}#message,#placeMessage,#followStatus{white-space:pre-wrap;color:#a8fac1}</style>
<h1>◉ FlightDot</h1><p id="live">Conectando…</p><p id="message" role="status"></p>
<section id="wifi"><h2>Conectar ao Wi-Fi</h2><form id="wifiForm"><label>Nome da rede (SSID)</label><input name="ssid" maxlength="32" required autocomplete="off"><label>Senha</label><input name="password" type="password" maxlength="63" autocomplete="new-password"><button class="primary">Conectar</button></form></section>
<section><h2>Pesquisar</h2><form id="placeSearch"><label for="placeQuery">Cidade ou aeroporto</label><input id="placeQuery" maxlength="100" required><button class="primary">Pesquisar local</button></form><p id="placeMessage" role="status"></p><div id="placeResults"></div><form id="flightSearch"><label for="flightQuery">Número do voo ou callsign</label><input id="flightQuery" maxlength="16" required autocapitalize="characters"><button class="primary">Seguir avião</button><button type="button" id="stopFollow" hidden>Parar de seguir</button></form><p id="followStatus" role="status"></p></section>
<section><h2>Radar</h2><form id="settings"><input name="lat" type="hidden"><input name="lon" type="hidden"><input name="centerName" type="hidden"><label>Alcance (km)</label><input name="rangeKm" type="number" min="10" max="250" required><label>Tema</label><select name="theme"><option value="0">Fósforo verde</option><option value="1">Âmbar CRT</option><option value="2">Vermelho</option><option value="3">Azul</option><option value="4">Verde neon</option></select><label>Brilho (10–255)</label><input name="brightness" type="range" min="10" max="255"><label>Avisar dados atrasados após (segundos)</label><input name="staleSeconds" type="number" min="10" max="300" required><label>Fuso horário</label><input name="timezone" maxlength="63" required><button type="button" onclick="browserZone()">Usar fuso do navegador</button><label><input name="sweep" type="checkbox" style="width:auto"> Linha de varredura</label><button class="primary">Salvar configurações</button></form></section>
<section><h2>Atualizar firmware</h2><form id="ota"><input type="file" name="firmware" accept=".bin" required><button>Instalar atualização</button></form><progress id="progress" max="100" value="0" hidden></progress></section>
<section><h2>Rede</h2><button onclick="resetWifi()">Esquecer Wi-Fi e abrir configuração</button><small>Dados: airplanes.live / ADSB.lol / <a href="https://adsb.fi/">adsb.fi</a>. Rotas: adsbdb. Clima: Open-Meteo. Locais: GeoNames / OurAirports.</small></section>
<script>
let token='',airportsPromise,placeBusy=false,lastPlaceSearch=0;const form=document.querySelector('#settings'),msg=t=>document.querySelector('#message').textContent=t,el=n=>form.elements.namedItem(n);
async function api(path,data){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','X-Radar-Token':token},body:new URLSearchParams(data)}),text=await r.text();if(!r.ok)throw Error(text);return text}
function setCenter(lat,lon,name){el('lat').value=lat;el('lon').value=lon;el('centerName').value=name.slice(0,30)}
function browserZone(){let z=Intl.DateTimeFormat().resolvedOptions().timeZone,known={'America/Sao_Paulo':'<-03>3','America/Manaus':'<-04>4','America/Fortaleza':'<-03>3','America/Recife':'<-03>3','America/New_York':'EST5EDT,M3.2.0,M11.1.0','Europe/Lisbon':'WET0WEST,M3.5.0/1,M10.5.0/2','Europe/London':'GMT0BST,M3.5.0/1,M10.5.0/2'},off=new Date().getTimezoneOffset(),sign=off<0?'-':'';el('timezone').value=known[z]||`LOC${sign}${Math.floor(Math.abs(off)/60)}:${String(Math.abs(off)%60).padStart(2,'0')}`}
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
function airportIndex(){if(!airportsPromise)airportsPromise=fetch('/api/airports').then(r=>{if(!r.ok)throw Error('Falha ao carregar aeroportos');return r.json()}).catch(e=>{airportsPromise=null;throw e});return airportsPromise}
async function cities(q){const key='city-v1:'+normalize(q);let saved;try{saved=JSON.parse(localStorage.getItem(key))}catch(e){}if(saved&&Date.now()-saved.at<86400000)return saved.items;const r=await fetch('https://geocoding-api.open-meteo.com/v1/search?'+new URLSearchParams({name:q,count:'8',language:'pt',format:'json'}),{signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('Busca de cidades indisponível');const body=await r.json(),items=(body.results||[]).map(x=>({name:[x.name,x.admin1,x.country].filter(Boolean).join(' · '),label:x.name,lat:x.latitude,lon:x.longitude,kind:'Cidade'}));try{localStorage.setItem(key,JSON.stringify({at:Date.now(),items}))}catch(e){}return items}
document.querySelector('#placeSearch').onsubmit=async e=>{e.preventDefault();if(placeBusy||Date.now()-lastPlaceSearch<1200)return;placeBusy=true;lastPlaceSearch=Date.now();const btn=e.target.querySelector('button'),info=document.querySelector('#placeMessage'),results=document.querySelector('#placeResults');btn.disabled=true;results.replaceChildren();info.textContent='Pesquisando…';const query=document.querySelector('#placeQuery').value.trim(),q=normalize(query);try{if(q.length<2)throw Error('Digite ao menos dois caracteres.');const found=await Promise.allSettled([airportIndex(),cities(query)]);let items=[];if(found[0].status==='fulfilled')items=found[0].value.filter(a=>normalize(a.slice(0,5).join(' ')).includes(q)).sort((a,b)=>{const score=x=>(normalize(x[2])===q||normalize(x[3])===q?100:0)+(x[4]==='BR'?10:0)+(x[2]?1:0);return score(b)-score(a)}).slice(0,8).map(a=>({name:[a[0],a[1],[a[2],a[3]].filter(Boolean).join('/'),a[4]].filter(Boolean).join(' · '),label:a[1]||a[0],lat:a[5],lon:a[6],kind:'Aeroporto'}));if(found[1].status==='fulfilled')items.push(...found[1].value);for(const item of items){const b=document.createElement('button');b.type='button';b.style.cssText='display:block;width:100%;text-align:left';b.textContent=item.kind+': '+item.name;b.onclick=async()=>{b.disabled=true;try{await api('/api/follow',{query:''});setCenter(item.lat,item.lon,item.label);await saveSettings();info.textContent='Centralizado em '+item.label}catch(e){info.textContent=e.message}finally{b.disabled=false}};results.append(b)}info.textContent=items.length?'Escolha um resultado.':'Nenhum local encontrado.'}catch(e){info.textContent=e.message}finally{btn.disabled=false;placeBusy=false}};
document.querySelector('#flightSearch').onsubmit=async e=>{e.preventDefault();try{msg(await api('/api/follow',{query:document.querySelector('#flightQuery').value}));await status()}catch(e){msg(e.message)}};document.querySelector('#stopFollow').onclick=async()=>{try{msg(await api('/api/follow',{query:''}));await status()}catch(e){msg(e.message)}};
async function saveSettings(){let d=Object.fromEntries(new FormData(form));d.sweep=el('sweep').checked?'1':'0';const result=await api('/api/config',d);msg(result);return result}form.onsubmit=async e=>{e.preventDefault();try{await saveSettings()}catch(e){msg(e.message)}};document.querySelector('#wifiForm').onsubmit=async e=>{e.preventDefault();try{msg(await api('/api/wifi',Object.fromEntries(new FormData(e.target))))}catch(e){msg(e.message)}};async function resetWifi(){if(confirm('Esquecer a rede Wi-Fi salva?'))try{msg(await api('/api/reset-wifi',{}))}catch(e){msg(e.message)}}
document.querySelector('#ota').onsubmit=e=>{e.preventDefault();if(!confirm('Instalar o firmware e reiniciar o radar?'))return;let x=new XMLHttpRequest();x.open('POST','/update?token='+encodeURIComponent(token));x.setRequestHeader('Authorization','Basic '+btoa('admin:'+prompt('Senha OTA:')));x.upload.onprogress=e=>{let p=document.querySelector('#progress');p.hidden=false;if(e.lengthComputable)p.value=e.loaded/e.total*100};x.onload=()=>msg(x.responseText);x.onerror=()=>msg('Conexão encerrada. Verifique se o radar reiniciou.');x.send(new FormData(e.target))};
async function start(){try{const s=await(await fetch('/api/config')).json();token=s.token;for(const k of ['lat','lon','centerName','rangeKm','theme','brightness','staleSeconds','timezone'])el(k).value=s[k];el('sweep').checked=s.sweep;document.querySelector('#wifi').hidden=!s.portal}catch(e){msg('Falha ao carregar: '+e.message)}}async function status(){try{const s=await(await fetch('/api/status')).json();document.querySelector('#live').textContent=`${s.wifi?'Conectado':'Configuração Wi-Fi'} · ${s.count} voos · ${s.provider||'aguardando'}${s.error?' · '+s.error:''}`;document.querySelector('#stopFollow').hidden=!s.follow;document.querySelector('#followStatus').textContent=s.follow?`${s.target?'Seguindo':'Buscando'} ${s.follow}${s.target?' · '+s.target.callsign:''}`:''}catch(e){}}start();status();setInterval(status,5000);
</script></html>)HTML";
